---
title: "longumi comparison"
author:
  - name: Yan Hui
    affiliation: Department of Food Science, University of Copenhagen
    email: huiyan@food.ku.dk
date: 05/10/2023
output:
  html_document:
    toc: true
link-citations: yes
bibliography: ref.bib
csl: cell.csl
---

```{r, error profile, eval = FALSE}
source("./scripts/validation_functions.R")
dir.create("data/longumi1000000", showWarnings = FALSE)
qc_complie <- function(
  qc_dir,
  consensus_prefix,
  reference="zymo-ref-uniq_2019-10-28.fa",
  read_data,
  bin_map="bin_map.txt",
  outprefix){
  # load files
  dir.create(dirname(outprefix), showWarnings = FALSE, recursive = TRUE)
  lu_compile_qc(
    data_dir = qc_dir,
    umi_consensus = paste0(consensus_prefix, ".fa"),
    reference = reference,
    read_data = read_data,
    umi_bin_map = bin_map,
    out_path = paste0(outprefix, "_qc.Rdata")
    )
  ep <- lu_error_profile(
    refs = paste0(qc_dir, "/", reference),
    sam = paste0(qc_dir, "/", consensus_prefix, ".sam")
    )
  save(ep, file = paste0(outprefix, "_ep.Rdata"))
  }

# prepare a dataframe for loop
fs <- list.files(
  path = "/mnt/md0/UMI16S/cp2/latest/longumi/qc/sub1000000",
  pattern = "*bin_map.txt", full.names = TRUE, recursive = TRUE)
df <- data.frame(bin_map = fs)
df$qc_dir <- dirname(df$bin_map)
df$data <- gsub("^.*qc/sub1000000/(.*)/(.*)/qc$", "\\1", df$qc_dir) #nolint
df$consensus <- gsub("^.*qc/sub1000000/(.*)/(.*)/qc$", "\\2", df$qc_dir) #nolint
df$consensus_prefix <- case_when(
  df$consensus == "umiCon" | df$consensus == "umiConN" ~ "umiCon_trimmed",
  TRUE ~ df$consensus
)
df$read_data <- case_when(
  df$data == "pb_ccs" ~ "ccs_sub1000000_s11.fa",
  df$data == "zymock_r9" ~ "ERR3336963_1sub1000000_s123.fa",
  df$data == "zymock_r10" ~ "ERR3813594_1sub1000000_s123.fa"
)
df$outprefix <- paste0("data/longumi/", df$data, "/", df$consensus)

for (i in seq_len(nrow(df))) {
  qc_complie(
    qc_dir = df$qc_dir[i],
    consensus_prefix = df$consensus_prefix[i],
    read_data = df$read_data[i],
    outprefix = df$outprefix[i]
  )
}
```

```{r, size_cutoff}
source("./scripts/validation_functions.R")
rds <- list.files(
  path = "./data/longumi1000000",
  pattern = "*.Rdata", full.names = TRUE, recursive = TRUE)
# qcs: *_qc.Rdata; eps: *_ep.Rdata
qcs <- rds[grep("_qc.Rdata$", rds)]
eps <- rds[grep("_ep.Rdata$", rds)]
df <- data.frame(qc = qcs, ep = eps)
df$data <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\1", df$qc)
df$consensus <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\2", df$qc)
# merge qcs into one
qc_from_rds <- function(rds, filter = FALSE, size = NULL) {
  load(rds)
  if (filter) {
    qc <- filter(
      qc,
      !is.na(length) # remove umi bins not aligned to ref.
    )

    # if rds not contains umiCon, use quantile 0, 0.25 , 0.5, 0.75
    if (grepl("umiCon", rds)) {
      breaks <- c(seq(1, 60, 3), Inf)
    } else {
      breaks <- c(quantile(qc$umi_cluster_size)[1:4], Inf)
      }

    outlier <- lu_artefact_plot(
      qc,
      breaks = breaks) %>% 
      .$data %>%
      filter(
      aflag == "lightblue"
      )
    # contamination
    cont <- outlier %>%
    select(umi, ref_ssu_error, silva_ssu_error) %>%
    filter(silva_ssu_error < ref_ssu_error &  0.1 < ref_ssu_error - silva_ssu_error) %>% #nolint
    arrange(desc(ref_ssu_error - silva_ssu_error)) %>%
    mutate(flag = "cont")
    # chimera
    chi <- outlier %>%
    select(umi, chimera) %>%
    filter(chimera == "Y" & !(umi %in% cont$umi)) %>%
    mutate(flag = "chi")

    qc <- filter(
      qc,
    !(umi %in% cont$umi),
    !(umi %in% chi$umi),
    )
  }
  if (!is.null(size)) {
    qc <- filter(
      qc,
      umi_cluster_size >= size
    )
  }
  return(qc)
}
library(data.table)
dt_qc <- rbindlist(sapply(df$qc, qc_from_rds, simplify = FALSE), idcol = "file", use.names = FALSE) #nolint
dt_qc$data <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\1", dt_qc$file) #nolint
dt_qc$consensus <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\2", dt_qc$file) #nolint

dt_qc_f <- rbindlist(sapply(df$qc, qc_from_rds, filter = TRUE, simplify = FALSE), idcol = "file", use.names = FALSE) #nolint
dt_qc_f$data <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\1", dt_qc_f$file) #nolint
dt_qc_f$consensus <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\2", dt_qc_f$file) #nolint

dt_cutoff <- dt_qc_f %>%
  select(data, consensus) %>%
  distinct() %>%
  mutate(cutoff=case_when(
    df$data == "zymock_r10" & df$consensus == "umiCon" ~ 15,
    df$data == "zymock_r9" & df$consensus == "umiCon" ~ 25,
    consensus %in% c("kmerCon", "miniCon", "isoCon") ~ 150, #nobin
    TRUE ~ 4
  ), y= Inf) %>%
  mutate(x = case_when(
    consensus == "kmerCon" ~ cutoff + 500,
    consensus %in% c("miniCon", "isoCon") ~ cutoff + 200,
    TRUE ~ cutoff + 0.5
  ))
dt_cutoff$label <- sapply(dt_cutoff$cutoff, function(x) paste0(x, "x"))

# draw a simple plot
library(ggprism)
library(RColorBrewer)
stat_jitter_xy <- function(dt, column_x, column_y) {
  p <- dt %>%
  ggplot(aes(
    y = .data[[column_y]], 
    x = .data[[column_x]],
      )) +
  geom_point(
    aes(color = factor(
      data, 
      levels = c("pb_ccs", "zymock_r10", "zymock_r9"),
      labels = c("PacBio CCS", "ONT R10.3", "ONT R9.4.1")
      ))) +
  scale_color_manual(values = brewer.pal(4, "Spectral")[c(4,2,1)]) +
  facet_grid(
    factor(data, labels = c("PacBio CCS", "ONT R10.3", "ONT R9.4.1")) ~ #nolint 
    fct_relevel(consensus, "kmerCon", "miniCon", "isoCon", "umiCon"), scales = "free") + #nolint
  labs(
    x = "# of reads",
    y = "% of errors",
    color = "Data",
    ) +
  geom_vline(data = dt_cutoff, aes(xintercept = cutoff), linetype = "dashed") + #nolint
  geom_text(data = dt_cutoff, aes(x = x, y = y, label = label), hjust=0, vjust = 1) + #nolint
  theme_prism() +
  theme(
    legend.title = element_text(),
    axis.text.x = element_text(angle = 90),
  )
  return(p)
}

p_size_err <- stat_jitter_xy(dt_qc, column_y = "ref_error", column_x = "umi_cluster_size")
p_size_err_f <- stat_jitter_xy(dt_qc_f, column_y = "ref_error", column_x = "umi_cluster_size")
dir.create("./figure/longumi1000000", showWarnings = FALSE, recursive = TRUE)
ggsave("./figure/longumi1000000/size_err.png", p_size_err, width = 12, height = 8) #nolint
ggsave("./figure/longumi1000000/size_err_f.png", p_size_err_f, width = 12, height = 8) #nolint
```

```{r, stats}
source("./scripts/validation_functions.R")
rds <- list.files(
  path = "./data/longumi",
  pattern = "*.Rdata", full.names = TRUE, recursive = TRUE)
# qcs: *_qc.Rdata; eps: *_ep.Rdata
qcs <- rds[grep("_qc.Rdata$", rds)]
eps <- rds[grep("_ep.Rdata$", rds)]
df <- data.frame(qc = qcs, ep = eps)
df$data <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\1", df$qc)
df$consensus <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\2", df$qc)
df$cutoff <- case_when(
  df$data == "zymock_r10" & df$consensus == "umiCon" ~ 15,
  df$data == "zymock_r9" & df$consensus == "umiCon" ~ 25,
  df$consensus %in% c("kmerCon", "miniCon", "isoCon") ~ 150, # chimera
  TRUE ~ 3
)

# overview stats
nclusters_from_rds <- function(rds, filter=FALSE, size = NULL) {
  load(rds)
  if (filter) {
    qc <- filter(
      qc,
      !is.na(length) # remove umi bins not aligned to ref.
    )

    # if rds not contains umiCon, use quantile 0, 0.25 , 0.5, 0.75
    if (grepl("umiCon", rds)) {
      breaks <- c(seq(1, 60, 3), Inf)
    } else {
      breaks <- c(quantile(qc$umi_cluster_size)[1:4], Inf)
      }

    outlier <- lu_artefact_plot(
      qc,
      breaks = breaks) %>% 
      .$data %>%
      filter(
      aflag == "lightblue"
      )
    # contamination
    cont <- outlier %>%
    select(umi, ref_ssu_error, silva_ssu_error) %>%
    filter(silva_ssu_error < ref_ssu_error &  0.1 < ref_ssu_error - silva_ssu_error) %>% #nolint
    arrange(desc(ref_ssu_error - silva_ssu_error)) %>%
    mutate(flag = "cont")
    qc <- filter(
      qc,
    !(umi %in% cont$umi)
    )
  }
  if (!is.null(size)) {
    qc <- filter(
      qc,
      umi_cluster_size >= size
    )
  }
  nclusters <- length(unique(qc$umi))
  return(nclusters)
}

nrefs_from_rds <- function(rds, filter=FALSE, size = NULL) {
  load(rds)
  if (filter) {
    qc <- filter(
      qc,
      !is.na(length) # remove umi bins not aligned to ref.
    )

    # if rds not contains umiCon, use quantile 0, 0.25 , 0.5, 0.75
    if (grepl("umiCon", rds)) {
      breaks <- c(seq(1, 60, 3), Inf)
    } else {
      breaks <- c(quantile(qc$umi_cluster_size)[1:4], Inf)
      }

    outlier <- lu_artefact_plot(
      qc,
      breaks = breaks) %>% 
      .$data %>%
      filter(
      aflag == "lightblue"
      )
    # contamination
    cont <- outlier %>%
    select(umi, ref_ssu_error, silva_ssu_error) %>%
    filter(silva_ssu_error < ref_ssu_error &  0.1 < ref_ssu_error - silva_ssu_error) %>% #nolint
    arrange(desc(ref_ssu_error - silva_ssu_error)) %>%
    mutate(flag = "cont")
    qc <- filter(
      qc,
    !(umi %in% cont$umi)
    )
  }
  if (!is.null(size)) {
    qc <- filter(
      qc,
      umi_cluster_size >= size
    )
  }
  # unique ref_tax with no NAs
  nrefs <- sum(!is.na(unique(qc$ref_tax)))
  return(nrefs)
}

chimera_from_rds <- function(rds, filter=TRUE, size = NULL) {
  load(rds)
  if (filter) {
    qc <- filter(
      qc,
      !is.na(length) # remove umi bins not aligned to ref.
    )

    # if rds not contains umiCon, use quantile 0, 0.25 , 0.5, 0.75
    if (grepl("umiCon", rds)) {
      breaks <- c(seq(1, 60, 3), Inf)
    } else {
      breaks <- c(quantile(qc$umi_cluster_size)[1:4], Inf)
      }

    outlier <- lu_artefact_plot(
      qc,
      breaks = breaks) %>% 
      .$data %>%
      filter(
      aflag == "lightblue"
      )
    # contamination
    cont <- outlier %>%
    select(umi, ref_ssu_error, silva_ssu_error) %>%
    filter(silva_ssu_error < ref_ssu_error &  0.1 < ref_ssu_error - silva_ssu_error) %>% #nolint
    arrange(desc(ref_ssu_error - silva_ssu_error)) %>%
    mutate(flag = "cont")
    # chimera
    chi <- outlier %>%
    select(umi, chimera) %>%
    filter(chimera == "Y" & !(umi %in% cont$umi)) %>%
    mutate(flag = "chi")
    if (!is.null(size)) {
      qc <- filter(
        qc,
        umi_cluster_size >= size
        )
      }
    # calculate chimera rate
    chimerate <- qc %>%
    filter(
      !(umi %in% cont$umi),
      ) %>%
      {nrow(chi)/nrow(.)*100}
  }
  else {
    if (!is.null(size)) {
      qc <- filter(
        qc,
        umi_cluster_size >= size
        )
      }
    # chimerate by uchime-ref without extra qc
    chimerate <- qc %>%
    filter(
      chimera == "Y"
      ) %>%
      {nrow(.) / nrow(qc) * 100}
  }
  return(chimerate)
}

df$nclusters <- mapply(function(x, y) nclusters_from_rds(x, filter=FALSE, size=y), df$qc, df$cutoff) #nolint
df$nclusters_f <- mapply(function(x, y) nclusters_from_rds(x, filter=TRUE, size=y), df$qc, df$cutoff) #nolint
# in total, nrefs = 43
df$nrefs <- mapply(function(x, y) nrefs_from_rds(x, filter=FALSE, size=y), df$qc, df$cutoff) #nolint
df$nrefs_f <- mapply(function(x, y) nrefs_from_rds(x, filter=TRUE, size=y), df$qc, df$cutoff) #nolint
df$chimerate <- mapply(function(x, y) chimera_from_rds(x, filter=FALSE, size=y), df$qc, df$cutoff) #nolint
df$chimerate_f <- mapply(function(x, y) chimera_from_rds(x, filter=TRUE, size=y), df$qc, df$cutoff) #nolint
# draw a simple plot
library(ggprism)
library(RColorBrewer)
stat_bar <- function(df, column, y_lab, y_int=NULL) {
  p <- df %>%
  ggplot(aes(
    y = .data[[column]], 
    x = fct_relevel(consensus, "kmerCon", "miniCon", "isoCon", "umiCon"))) +
  geom_bar(
    stat = "identity",
    position="dodge",
    aes(fill = factor(
      data, 
      levels = c("pb_ccs", "zymock_r10", "zymock_r9"),
      labels = c("PacBio CCS", "ONT R10.3", "ONT R9.4.1")
      ))) +
  {if(! is.null(y_int))geom_hline(yintercept = y_int, linetype = "dashed")} +
  scale_fill_manual(values = brewer.pal(4, "Spectral")[c(4,2,1)]) +
  labs(
    x = "",
    y = y_lab,
    fill = "Data",
    ) +
  theme_prism() +
  theme(
    legend.title = element_text(),
    axis.text.x = element_text(angle = 90),
  )
  return(p)
}
p_nclusters <- stat_bar(df, "nclusters", "# of clusters")
p_nclusters_f <- stat_bar(df, "nclusters_f", "# of clusters")
p_refs <- stat_bar(df, "nrefs", "# of references", y_int = 43)
p_refs_f <- stat_bar(df, "nrefs_f", "# of references", y_int = 43)
p_chimerate <- stat_bar(df, "chimerate", "% of chimeras")
p_chimerate_f <- stat_bar(df, "chimerate_f", "% of chimeras")
library(patchwork)
p_stat_overview <- p_nclusters + p_refs + p_chimerate + plot_layout(guides = "collect") #nolint
#p_stat_overview
p_stat_overview_f <- p_nclusters_f + p_refs_f + p_chimerate_f + plot_layout(guides = "collect") #nolint
#p_stat_overview_f

# consensus stats
# merge qcs into one
qc_from_rds <- function(rds, filter = FALSE, size = NULL) {
  load(rds)
  if (filter) {
    qc <- filter(
      qc,
      !is.na(length) # remove umi bins not aligned to ref.
    )

    # if rds not contains umiCon, use quantile 0, 0.25 , 0.5, 0.75
    if (grepl("umiCon", rds)) {
      breaks <- c(seq(1, 60, 3), Inf)
    } else {
      breaks <- c(quantile(qc$umi_cluster_size)[1:4], Inf)
      }

    outlier <- lu_artefact_plot(
      qc,
      breaks = breaks) %>% 
      .$data %>%
      filter(
      aflag == "lightblue"
      )
    # contamination
    cont <- outlier %>%
    select(umi, ref_ssu_error, silva_ssu_error) %>%
    filter(silva_ssu_error < ref_ssu_error &  0.1 < ref_ssu_error - silva_ssu_error) %>% #nolint
    arrange(desc(ref_ssu_error - silva_ssu_error)) %>%
    mutate(flag = "cont")
    # chimera
    chi <- outlier %>%
    select(umi, chimera) %>%
    filter(chimera == "Y" & !(umi %in% cont$umi)) %>%
    mutate(flag = "chi")

    qc <- filter(
      qc,
    !(umi %in% cont$umi),
    !(umi %in% chi$umi),
    )
  }
  if (!is.null(size)) {
    qc <- filter(
      qc,
      umi_cluster_size >= size
    )
  }
  return(qc)
}
library(data.table)
#dt_qc <- rbindlist(sapply(df$qc, qc_from_rds, simplify = FALSE), idcol = "file", use.names = FALSE) #nolint
dt_qc <- rbindlist(mapply(function(x, y) qc_from_rds(x, filter = FALSE, size = y), df$qc, df$cutoff, SIMPLIFY = FALSE), idcol = "file", use.names = FALSE) #nolint
dt_qc$data <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\1", dt_qc$file) #nolint
dt_qc$consensus <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\2", dt_qc$file) #nolint

#dt_qc_f <- rbindlist(sapply(df$qc, qc_from_rds, filter = TRUE, simplify = FALSE), idcol = "file", use.names = FALSE) #nolint
dt_qc_f <- rbindlist(mapply(function(x, y) qc_from_rds(x, filter = TRUE, size = y), df$qc, df$cutoff, SIMPLIFY = FALSE), idcol = "file", use.names = FALSE) #nolint
dt_qc_f$data <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\1", dt_qc_f$file) #nolint
dt_qc_f$consensus <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\2", dt_qc_f$file) #nolint

stat_jitter <- function(dt, column, y_lab, y_int=NULL) {
  p <- dt %>%
  ggplot(aes(
    y = .data[[column]], 
    x = fct_relevel(consensus, "kmerCon", "miniCon", "isoCon", "umiCon"))) +
  geom_jitter(
    position = position_jitterdodge(dodge.width = 0.9),
    aes(color = factor(
      data, 
      levels = c("pb_ccs", "zymock_r10", "zymock_r9"),
      labels = c("PacBio CCS", "ONT R10.3", "ONT R9.4.1")
      ))) +
  {if(! is.null(y_int))geom_hline(yintercept = y_int, linetype = "dashed")} +
  scale_color_manual(values = brewer.pal(4, "Spectral")[c(4,2,1)]) +
  labs(
    x = "",
    y = y_lab,
    color = "Data",
    ) +
  theme_prism() +
  theme(
    legend.title = element_text(),
    axis.text.x = element_text(angle = 90),
  )
  return(p)
}
p_cont <- stat_jitter(dt_qc, "contamination", "% of contamination")
p_cont_f <- stat_jitter(dt_qc_f, "contamination", "% of contamination")
p_len <- stat_jitter(dt_qc, "length", "Consensus length (bp)")
p_len_f <- stat_jitter(dt_qc_f, "length", "Consensus length (bp)")
p_error <- stat_jitter(dt_qc, "ref_error", "% of errors")
p_error_f <- stat_jitter(dt_qc_f, "ref_error", "% of errors")

p_stat_consensus <- p_len + p_cont + p_error + plot_layout(guides = "collect") #nolint
p_stat_consensus_f <- p_len_f + p_cont_f + p_error_f + plot_layout(guides = "collect") #nolint  
#p_stat_consensus_f
#p_stat_consensus

# stat by error type
errorsum_from_rds <- function(rds_qc, rds_ep, filter = FALSE, size= NULL) {
  qcf <- qc_from_rds(rds_qc, filter = filter, size = size)
  load(rds_ep)
  epf <- filter(
    ep,
    sub(";.*", "", qname) %in% qcf$umi,
    )
  sum <- lu_errortype_summary(
    profile = epf,
    digits = 4,
    title = NULL
    )
  colnames(sum) <- c("region", "mismatch", "insertion", "deletion", "total")
  sum_long <- sum %>%
    pivot_longer(!region, names_to = "type", values_to = "pct")
  return(sum_long)
  } 

# Ref homopolymer statistics
ref_hp <- Biostrings::readDNAStringSet("/mnt/md0/UMI16S/cp2/latest/longumi/qc/sub100000/pb_ccs/umiCon/qc/zymo-ref-uniq_2019-10-28.fa") %>% #nobin
  lu_ref_hp_pos()

dt_sum <- rbindlist(mapply(function(x,y,z) errorsum_from_rds(x, y, filter = FALSE, size = z), df$qc, df$ep, df$cutoff, SIMPLIFY = FALSE), idcol = "file", use.names = FALSE) #nolint
dt_sum$data <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\1", dt_sum$file) #nolint
dt_sum$consensus <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\2", dt_sum$file) #nolint

dt_sum_f <- rbindlist(mapply(function(x,y,z) errorsum_from_rds(x, y, filter = TRUE, size = z), df$qc, df$ep, df$cutoff, SIMPLIFY = FALSE), idcol = "file", use.names = FALSE) #nolint
dt_sum_f$data <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\1", dt_sum_f$file) #nolint
dt_sum_f$consensus <- gsub("^.*longumi/(.*)/(.*)_qc.Rdata", "\\2", dt_sum_f$file) #nolint
save(dt_sum, dt_sum_f, file = "./data/longumi1000000_sumerr.Rdata")
```

```{r, stat_sum}
library(ggplot2)
library(ggprism)
load("./data/longumi1000000_sumerr.Rdata")
dir.create("./table/longumi", showWarnings = FALSE, recursive = TRUE)
write.csv(dt_sum[, -1], "./table/longumi/umi1000000_sumerr.csv", quote = FALSE, row.names = FALSE) #nolint
write.csv(dt_sum_f[, -1], "./table/longumi/umi1000000_sumerr_f.csv", quote = FALSE, row.names = FALSE) #nolint
stat_col <- function(dt, column, y_lab, title, y_int=NULL) {
  p <- dt %>%
  ggplot(aes(
    y = .data[[column]], 
    x = fct_relevel(consensus, "kmerCon", "miniCon", "isoCon", "umiCon"))) +
  geom_col(
    position = position_dodge(),
    aes(
      color = factor(
        type,
        levels = c("total","mismatch", "insertion", "deletion"),
        labels = c("Total","Mismatch", "Insertion", "Deletion")),
      fill = factor(
        type,
        levels = c("total","mismatch", "insertion", "deletion"),
        labels = c("Total","Mismatch", "Insertion", "Deletion")),
      )) +
  labs(
    title = title,
    x = "",
    y = y_lab,
    fill = "Error type",
    color = "Error type"
    ) +
  facet_grid(. ~ factor(
        data, 
        levels = c("pb_ccs", "zymock_r10", "zymock_r9"),
        labels = c("PacBio CCS", "ONT R10.3", "ONT R9.4.1")) #nolint
        ) +
  theme_prism() +
  theme(
    legend.title = element_text(),
    axis.text.x = element_text(angle = 90),
    strip.text = element_text(size = 8)
  )
  return(p)
}

p_errall <- dt_sum %>%
  filter(region == "all") %>%
  stat_col("pct", "% of error", "All")
p_errhp0 <- dt_sum %>%
  filter(region == "hp-") %>%
  stat_col("pct", "% of error", "HP-")
p_errhp1 <- dt_sum %>%
  filter(region == "hp+") %>%
  stat_col("pct", "% of error", "HP+")

p_errall_f <- dt_sum_f %>%
  filter(region == "all") %>%
  stat_col("pct", "% of error", "All")
p_errhp0_f <- dt_sum_f %>%
  filter(region == "hp-") %>%
  stat_col("pct", "% of error", "HP-")
p_errhp1_f <- dt_sum_f %>%
  filter(region == "hp+") %>%
  stat_col("pct", "% of error", "HP+")

library(patchwork)
p_stat_err <- p_errall + p_errhp0 + p_errhp1 + plot_layout(guides = "collect") # nolint
p_stat_err_f <- p_errall_f + p_errhp0_f + p_errhp1_f + plot_layout(guides = "collect") # nolint
```

```{r, ggsave}
dir.create("./figure/longumi1000000", showWarnings = FALSE)
ggsave("./figure/longumi1000000/stat_overview.png", p_stat_overview, width = 12, height = 4) #nolint
ggsave("./figure/longumi1000000/stat_overview_f.png", p_stat_overview_f, width = 12, height = 4) #nolint
ggsave("./figure/longumi1000000/stat_consensus.png", p_stat_consensus, width = 12, height = 4) #nolint
ggsave("./figure/longumi1000000/stat_consensus_f.png", p_stat_consensus_f, width = 12, height = 4) #nolint
ggsave("./figure/longumi1000000/stat_err.png", p_stat_err, width = 12, height = 4) #nolint
ggsave("./figure/longumi1000000/stat_err_f.png", p_stat_err_f, width = 12, height = 4) #nolint

p_longumi <- (p_nclusters + labs(tag = "a") + p_refs + p_chimerate + plot_layout(guides = "collect")) / #nolint
  (p_errall + labs(tag="b") + p_errhp0 + p_errhp1 + plot_layout(guides = "collect"))  #nolint
p_longumi_f <- (p_nclusters_f + labs(tag = "a") + p_refs_f + p_chimerate_f + plot_layout(guides = "collect")) / #nolint
  (p_errall_f + labs(tag="b") + p_errhp0_f + p_errhp1_f + plot_layout(guides = "collect"))  #nolint
ggsave("./figure/longumi1000000/longumi.png", p_longumi, width = 12, height = 8) #nolint
ggsave("./figure/longumi1000000/longumi_f.png", p_longumi_f, width = 12, height = 8) #nolint

# all 3
p_longumi3 <- (p_nclusters + labs(tag = "a") + p_refs + p_chimerate + plot_layout(guides = "collect")) / #nolint
  (p_len + labs(tag="b") + p_cont + p_error + plot_layout(guides = "collect")) / #nolint
  (p_errall + labs(tag="c") + p_errhp0 + p_errhp1 + plot_layout(guides = "collect"))  #nolint
p_longumi3_f <- (p_nclusters_f + labs(tag = "a") + p_refs_f + p_chimerate_f + plot_layout(guides = "collect")) / #nolint
  (p_len_f + labs(tag="b") + p_cont_f + p_error_f + plot_layout(guides = "collect")) / #nolint
  (p_errall_f + labs(tag="c") + p_errhp0_f + p_errhp1_f + plot_layout(guides = "collect"))  #nolint
ggsave("./figure/longumi1000000/longumi3.png", p_longumi3, width = 12, height = 12) #nolint
ggsave("./figure/longumi1000000/longumi3_f.png", p_longumi3_f, width = 12, height = 12) #nolint
```